# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'infodiversas_inter.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(785, 538)
        MainWindow.setMinimumSize(QtCore.QSize(785, 538))
        MainWindow.setMaximumSize(QtCore.QSize(785, 538))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(190, 30, 431, 31))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(310, 410, 171, 71))
        self.label_2.setStyleSheet("image: url(:/informacoesdiversasdoc/login (2).png);")
        self.label_2.setObjectName("label_2")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(200, 60, 391, 41))
        self.label_4.setObjectName("label_4")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(150, 100, 481, 31))
        self.label_8.setObjectName("label_8")
        self.inputnovoserv = QtWidgets.QLineEdit(self.centralwidget)
        self.inputnovoserv.setGeometry(QtCore.QRect(110, 140, 261, 31))
        self.inputnovoserv.setObjectName("inputnovoserv")
        self.inputinfo = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.inputinfo.setGeometry(QtCore.QRect(110, 180, 591, 191))
        self.inputinfo.setObjectName("inputinfo")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(650, 20, 111, 151))
        self.label_3.setStyleSheet("image: url(:/informacoesdiversasdoc/2018-11-09-145251.308003Informacoes-Classificadas.png);")
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(584, 410, 111, 65))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.btnconsulta = QtWidgets.QPushButton(self.layoutWidget)
        self.btnconsulta.setObjectName("btnconsulta")
        self.verticalLayout.addWidget(self.btnconsulta)
        self.btnsair = QtWidgets.QPushButton(self.layoutWidget)
        self.btnsair.setObjectName("btnsair")
        self.verticalLayout.addWidget(self.btnsair)
        self.layoutWidget1 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget1.setGeometry(QtCore.QRect(110, 370, 103, 130))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.btnatuali = QtWidgets.QPushButton(self.layoutWidget1)
        self.btnatuali.setObjectName("btnatuali")
        self.verticalLayout_2.addWidget(self.btnatuali)
        self.btnvoltar = QtWidgets.QPushButton(self.layoutWidget1)
        self.btnvoltar.setObjectName("btnvoltar")
        self.verticalLayout_2.addWidget(self.btnvoltar)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Archer 1.0 - Atualizar/ Inserir"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">Archer -Sistema de notificações urgentes</span></p></body></html>"))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.label_4.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:11pt; font-weight:600;\">Atualizar/ Inserir informações diversas</span></p></body></html>"))
        self.label_8.setText(_translate("MainWindow", "Ferramenta apenas para usuários autorizados, uso exlcusivo de analistas de redes"))
        self.inputnovoserv.setPlaceholderText(_translate("MainWindow", "Digite o novo serviço / Informação:"))
        self.inputinfo.setPlaceholderText(_translate("MainWindow", "Digite as informações necessárias sobre esse serviço, ao terminar cliente em atualizar, ou inserir. Caso deseje, você pode consultar os serviços e informações já existentes, clicando no botão consulta."))
        self.btnconsulta.setText(_translate("MainWindow", "Consulta"))
        self.btnsair.setText(_translate("MainWindow", "Sair"))
        self.btnatuali.setText(_translate("MainWindow", "Atualizar/Inserir"))
        self.btnvoltar.setText(_translate("MainWindow", "Voltar"))
from atualizarinfo.informacoesdiversas import informacoesdiversasdoc_rc
