# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'atualizar_inter.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(785, 538)
        MainWindow.setMinimumSize(QtCore.QSize(785, 538))
        MainWindow.setMaximumSize(QtCore.QSize(785, 538))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(190, 30, 431, 31))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(320, 390, 171, 71))
        self.label_2.setStyleSheet("image: url(:/atualizardoc/scania-logo-2.png);")
        self.label_2.setObjectName("label_2")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(250, 70, 281, 41))
        self.label_4.setObjectName("label_4")
        self.btnsair = QtWidgets.QPushButton(self.centralwidget)
        self.btnsair.setGeometry(QtCore.QRect(600, 440, 93, 28))
        self.btnsair.setObjectName("btnsair")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(260, 140, 301, 241))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.btnatualizaragenda = QtWidgets.QPushButton(self.layoutWidget)
        self.btnatualizaragenda.setObjectName("btnatualizaragenda")
        self.verticalLayout_3.addWidget(self.btnatualizaragenda)
        self.btnatualizar = QtWidgets.QPushButton(self.layoutWidget)
        self.btnatualizar.setObjectName("btnatualizar")
        self.verticalLayout_3.addWidget(self.btnatualizar)
        self.layoutWidget1 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget1.setGeometry(QtCore.QRect(190, 150, 61, 221))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_7 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_7.setStyleSheet("image: url(:/atualizardoc/unnamed.png);")
        self.label_7.setText("")
        self.label_7.setObjectName("label_7")
        self.verticalLayout_4.addWidget(self.label_7)
        self.label_5 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_5.setStyleSheet("image: url(:/atualizardoc/wewev.png);")
        self.label_5.setObjectName("label_5")
        self.verticalLayout_4.addWidget(self.label_5)
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(150, 100, 481, 31))
        self.label_8.setObjectName("label_8")
        self.btnvoltar = QtWidgets.QPushButton(self.centralwidget)
        self.btnvoltar.setGeometry(QtCore.QRect(110, 440, 93, 28))
        self.btnvoltar.setObjectName("btnvoltar")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Archer 1.0 - Gerenciamento"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">Archer -Sistema de notificações urgentes</span></p></body></html>"))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.label_4.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:11pt; font-weight:600;\">Atualização de informações</span></p></body></html>"))
        self.btnsair.setText(_translate("MainWindow", "Sair"))
        self.btnatualizaragenda.setText(_translate("MainWindow", "Atualizar agenda de analistas On Call"))
        self.btnatualizar.setText(_translate("MainWindow", "Atualizar / Inserir informações diversas"))
        self.label_5.setText(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.label_8.setText(_translate("MainWindow", "Ferramenta apenas para usuários autorizados, uso exlcusivo de analistas de redes"))
        self.btnvoltar.setText(_translate("MainWindow", "Voltar"))
from atualizarinfo import atualizardoc_rc
