# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'decisaoabertura_inter.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(727, 523)
        MainWindow.setAccessibleDescription("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(170, 30, 431, 31))
        self.label.setObjectName("label")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(230, 100, 271, 41))
        self.label_4.setObjectName("label_4")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(310, 390, 121, 61))
        self.label_2.setStyleSheet("image: url(:/decisaoaberturadoc/scania-logo-2.png);")
        self.label_2.setObjectName("label_2")
        self.btnabertura = QtWidgets.QPushButton(self.centralwidget)
        self.btnabertura.setGeometry(QtCore.QRect(250, 210, 311, 41))
        self.btnabertura.setObjectName("btnabertura")
        self.btnconsultaranalistas = QtWidgets.QPushButton(self.centralwidget)
        self.btnconsultaranalistas.setGeometry(QtCore.QRect(250, 270, 311, 41))
        self.btnconsultaranalistas.setObjectName("btnconsultaranalistas")
        self.btnsairstauschamado = QtWidgets.QPushButton(self.centralwidget)
        self.btnsairstauschamado.setGeometry(QtCore.QRect(530, 410, 93, 28))
        self.btnsairstauschamado.setObjectName("btnsairstauschamado")
        self.btnvoltar = QtWidgets.QPushButton(self.centralwidget)
        self.btnvoltar.setGeometry(QtCore.QRect(100, 410, 93, 28))
        self.btnvoltar.setObjectName("btnvoltar")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(250, 170, 291, 31))
        self.label_3.setObjectName("label_3")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(110, 190, 101, 121))
        self.label_5.setStyleSheet("image: url(:/decisaoaberturadoc/1827402.png);")
        self.label_5.setObjectName("label_5")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Archer 1.0 - Status Abertura"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">Archer -Sistema de notificações urgentes</span></p></body></html>"))
        self.label_4.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:11pt; font-weight:600;\">Abertura de chamado</span></p></body></html>"))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.btnabertura.setText(_translate("MainWindow", "Notificar nova abertura de chamado"))
        self.btnconsultaranalistas.setText(_translate("MainWindow", "Consultar com analistas status dos chamados"))
        self.btnsairstauschamado.setText(_translate("MainWindow", "Sair"))
        self.btnvoltar.setText(_translate("MainWindow", "Voltar"))
        self.label_3.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:10pt;\">Escolha uma das opções abaixo:</span></p></body></html>"))
        self.label_5.setText(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>"))
from decisao import decisaoaberturadoc_rc
