# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login_inter.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(623, 502)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(100, 50, 431, 31))
        self.label.setObjectName("label")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(120, 200, 101, 81))
        self.label_3.setStyleSheet("image: url(:/logindoc/login (1).png);")
        self.label_3.setObjectName("label_3")
        self.inputemail = QtWidgets.QLineEdit(self.centralwidget)
        self.inputemail.setGeometry(QtCore.QRect(220, 140, 201, 31))
        self.inputemail.setText("")
        self.inputemail.setObjectName("inputemail")
        self.inputsenha = QtWidgets.QLineEdit(self.centralwidget)
        self.inputsenha.setGeometry(QtCore.QRect(220, 220, 201, 31))
        self.inputsenha.setText("")
        self.inputsenha.setEchoMode(QtWidgets.QLineEdit.Password)
        self.inputsenha.setObjectName("inputsenha")
        self.btnlogin = QtWidgets.QPushButton(self.centralwidget)
        self.btnlogin.setGeometry(QtCore.QRect(210, 290, 93, 28))
        self.btnlogin.setObjectName("btnlogin")
        self.btnsair = QtWidgets.QPushButton(self.centralwidget)
        self.btnsair.setGeometry(QtCore.QRect(330, 290, 93, 28))
        self.btnsair.setObjectName("btnsair")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(120, 120, 91, 61))
        self.label_5.setStyleSheet("image: url(:/logindoc/login (4).png);")
        self.label_5.setObjectName("label_5")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(230, 350, 171, 71))
        self.label_2.setStyleSheet("image: url(:/logindoc/login (2).png);")
        self.label_2.setObjectName("label_2")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Archer 1.0"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">Archer -Sistema de notificações urgentes</span></p></body></html>"))
        self.label_3.setText(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.inputemail.setPlaceholderText(_translate("MainWindow", "Digite seu e-mail:"))
        self.inputsenha.setPlaceholderText(_translate("MainWindow", "Digite sua senha:"))
        self.btnlogin.setText(_translate("MainWindow", "Login"))
        self.btnsair.setText(_translate("MainWindow", "Sair"))
        self.label_5.setText(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>"))
from login import logindoc_rc
