# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ping_inter.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(760, 559)
        MainWindow.setAccessibleDescription("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(160, 30, 431, 31))
        self.label.setObjectName("label")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(310, 80, 151, 31))
        self.label_4.setObjectName("label_4")
        self.btnsair = QtWidgets.QPushButton(self.centralwidget)
        self.btnsair.setGeometry(QtCore.QRect(580, 500, 93, 28))
        self.btnsair.setObjectName("btnsair")
        self.btnvoltar = QtWidgets.QPushButton(self.centralwidget)
        self.btnvoltar.setGeometry(QtCore.QRect(80, 500, 93, 28))
        self.btnvoltar.setObjectName("btnvoltar")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(80, 90, 161, 131))
        self.label_5.setStyleSheet("image: url(:/pingdoc/img_470459.png);")
        self.label_5.setObjectName("label_5")
        self.jaenlaresult = QtWidgets.QTextBrowser(self.centralwidget)
        self.jaenlaresult.setGeometry(QtCore.QRect(80, 250, 591, 191))
        self.jaenlaresult.setObjectName("jaenlaresult")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(280, 460, 181, 71))
        self.label_2.setStyleSheet("image: url(:/pingdoc/scania-logo-2.png);")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(270, 160, 384, 30))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_7 = QtWidgets.QLabel(self.layoutWidget)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout.addWidget(self.label_7)
        self.inputipping = QtWidgets.QLineEdit(self.layoutWidget)
        self.inputipping.setObjectName("inputipping")
        self.horizontalLayout.addWidget(self.inputipping)
        self.btnping = QtWidgets.QPushButton(self.layoutWidget)
        self.btnping.setObjectName("btnping")
        self.horizontalLayout.addWidget(self.btnping)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Archer 1.0 - Calculadora IP"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">Archer -Sistema de notificações urgentes</span></p></body></html>"))
        self.label_4.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; font-weight:600;\">PING</span></p></body></html>"))
        self.btnsair.setText(_translate("MainWindow", "Sair"))
        self.btnvoltar.setText(_translate("MainWindow", "Voltar"))
        self.label_5.setText(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.label_7.setText(_translate("MainWindow", "Endereço de IP ou Host:"))
        self.btnping.setText(_translate("MainWindow", "Pingar"))
from ping import pingdoc_rc
