# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'servicos_inter.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(807, 652)
        MainWindow.setMinimumSize(QtCore.QSize(807, 652))
        MainWindow.setMaximumSize(QtCore.QSize(807, 652))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(210, 30, 431, 31))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(350, 510, 171, 71))
        self.label_2.setStyleSheet("image: url(:/servicosdoc/scania-logo-2.png);")
        self.label_2.setObjectName("label_2")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(270, 70, 281, 41))
        self.label_4.setObjectName("label_4")
        self.btnsair = QtWidgets.QPushButton(self.centralwidget)
        self.btnsair.setGeometry(QtCore.QRect(640, 560, 93, 28))
        self.btnsair.setObjectName("btnsair")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(280, 140, 291, 371))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.btncalc = QtWidgets.QPushButton(self.layoutWidget)
        self.btncalc.setObjectName("btncalc")
        self.verticalLayout_3.addWidget(self.btncalc)
        self.btnconsultaportas = QtWidgets.QPushButton(self.layoutWidget)
        self.btnconsultaportas.setObjectName("btnconsultaportas")
        self.verticalLayout_3.addWidget(self.btnconsultaportas)
        self.btnconsultanalistas = QtWidgets.QPushButton(self.layoutWidget)
        self.btnconsultanalistas.setObjectName("btnconsultanalistas")
        self.verticalLayout_3.addWidget(self.btnconsultanalistas)
        self.btninformacoes = QtWidgets.QPushButton(self.layoutWidget)
        self.btninformacoes.setObjectName("btninformacoes")
        self.verticalLayout_3.addWidget(self.btninformacoes)
        self.btnatualizar = QtWidgets.QPushButton(self.layoutWidget)
        self.btnatualizar.setObjectName("btnatualizar")
        self.verticalLayout_3.addWidget(self.btnatualizar)
        self.btnping = QtWidgets.QPushButton(self.layoutWidget)
        self.btnping.setObjectName("btnping")
        self.verticalLayout_3.addWidget(self.btnping)
        self.btncadastrar = QtWidgets.QPushButton(self.layoutWidget)
        self.btncadastrar.setObjectName("btncadastrar")
        self.verticalLayout_3.addWidget(self.btncadastrar)
        self.layoutWidget1 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget1.setGeometry(QtCore.QRect(190, 150, 91, 351))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_3 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_3.setStyleSheet("image: url(:/servicosdoc/736663fe6f9e03fcb39ace9020c42b4c---cone-estacion--rio-de-calculadora-by-vexels.png);")
        self.label_3.setObjectName("label_3")
        self.verticalLayout_4.addWidget(self.label_3)
        self.label_6 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_6.setStyleSheet("image: url(:/servicosdoc/418414.png);")
        self.label_6.setObjectName("label_6")
        self.verticalLayout_4.addWidget(self.label_6)
        self.label_10 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_10.setStyleSheet("image: url(:/servicosdoc/275376.png);")
        self.label_10.setObjectName("label_10")
        self.verticalLayout_4.addWidget(self.label_10)
        self.label_11 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_11.setStyleSheet("image: url(:/servicosdoc/information-160885_960_720.png);")
        self.label_11.setObjectName("label_11")
        self.verticalLayout_4.addWidget(self.label_11)
        self.label_5 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_5.setStyleSheet("image: url(:/servicosdoc/wewev.png);")
        self.label_5.setObjectName("label_5")
        self.verticalLayout_4.addWidget(self.label_5)
        self.label_7 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_7.setStyleSheet("image: url(:/servicosdoc/ping-logo-png-transparent-svg-vector-freebie-supply-ping-png-2400_2400.png);")
        self.label_7.setText("")
        self.label_7.setObjectName("label_7")
        self.verticalLayout_4.addWidget(self.label_7)
        self.label_9 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_9.setStyleSheet("image: url(:/servicosdoc/unnamed.png);")
        self.label_9.setText("")
        self.label_9.setObjectName("label_9")
        self.verticalLayout_4.addWidget(self.label_9)
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(150, 110, 481, 31))
        self.label_8.setObjectName("label_8")
        self.btnsair_2 = QtWidgets.QPushButton(self.centralwidget)
        self.btnsair_2.setGeometry(QtCore.QRect(30, 580, 171, 31))
        self.btnsair_2.setObjectName("btnsair_2")
        self.proibidoatualizar = QtWidgets.QLabel(self.centralwidget)
        self.proibidoatualizar.setGeometry(QtCore.QRect(580, 360, 201, 31))
        self.proibidoatualizar.setText("")
        self.proibidoatualizar.setObjectName("proibidoatualizar")
        self.proibidocadastro = QtWidgets.QLabel(self.centralwidget)
        self.proibidocadastro.setGeometry(QtCore.QRect(590, 460, 181, 31))
        self.proibidocadastro.setText("")
        self.proibidocadastro.setObjectName("proibidocadastro")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Archer 1.0 - Serviços"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">Archer -Sistema de notificações urgentes</span></p></body></html>"))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.label_4.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">Serviços - Administrativa</span></p></body></html>"))
        self.btnsair.setText(_translate("MainWindow", "Sair"))
        self.btncalc.setText(_translate("MainWindow", "Caculadora de IP"))
        self.btnconsultaportas.setText(_translate("MainWindow", "Consulta de disponibilidade de portas"))
        self.btnconsultanalistas.setText(_translate("MainWindow", "Consulta de contato On Call Duty Analistas"))
        self.btninformacoes.setText(_translate("MainWindow", "Informações para abertura de chamado"))
        self.btnatualizar.setText(_translate("MainWindow", "Atualizar / Inserir informações"))
        self.btnping.setText(_translate("MainWindow", "Ping"))
        self.btncadastrar.setText(_translate("MainWindow", "Cadastro de usuários / analistas"))
        self.label_3.setText(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.label_6.setText(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.label_10.setText(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.label_11.setText(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.label_5.setText(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.label_8.setText(_translate("MainWindow", "Ferramenta apenas para usuários autorizados, uso exlcusivo de analistas de redes"))
        self.btnsair_2.setText(_translate("MainWindow", "Problemas com Archer?"))
from servicos import servicosdoc_rc
