# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'calc_inter.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(760, 559)
        MainWindow.setAccessibleDescription("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(160, 30, 431, 31))
        self.label.setObjectName("label")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(310, 90, 161, 31))
        self.label_4.setObjectName("label_4")
        self.btnsair = QtWidgets.QPushButton(self.centralwidget)
        self.btnsair.setGeometry(QtCore.QRect(580, 500, 93, 28))
        self.btnsair.setObjectName("btnsair")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(250, 170, 101, 16))
        self.label_7.setObjectName("label_7")
        self.inputip = QtWidgets.QLineEdit(self.centralwidget)
        self.inputip.setGeometry(QtCore.QRect(360, 170, 151, 21))
        self.inputip.setObjectName("inputip")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(250, 210, 101, 16))
        self.label_8.setObjectName("label_8")
        self.btncalcip = QtWidgets.QPushButton(self.centralwidget)
        self.btncalcip.setGeometry(QtCore.QRect(530, 190, 93, 28))
        self.btncalcip.setObjectName("btncalcip")
        self.btnvoltar = QtWidgets.QPushButton(self.centralwidget)
        self.btnvoltar.setGeometry(QtCore.QRect(80, 500, 93, 28))
        self.btnvoltar.setObjectName("btnvoltar")
        self.inputcidr = QtWidgets.QLineEdit(self.centralwidget)
        self.inputcidr.setGeometry(QtCore.QRect(360, 210, 151, 21))
        self.inputcidr.setObjectName("inputcidr")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(70, 130, 161, 131))
        self.label_5.setStyleSheet("image: url(:/calcdoc/png-transparent-calculator-computer-icons-button-cosmic-electronics-rectangle-calculator.png);")
        self.label_5.setObjectName("label_5")
        self.jaenlaresult = QtWidgets.QTextBrowser(self.centralwidget)
        self.jaenlaresult.setGeometry(QtCore.QRect(80, 290, 591, 131))
        self.jaenlaresult.setObjectName("jaenlaresult")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(320, 460, 121, 61))
        self.label_3.setStyleSheet("image: url(:/calcdoc/scania-logo-2.png);")
        self.label_3.setObjectName("label_3")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Archer 1.0 - Calculadora IP"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">Archer -Sistema de notificações urgentes</span></p></body></html>"))
        self.label_4.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">Calculadora Ip</span></p></body></html>"))
        self.btnsair.setText(_translate("MainWindow", "Sair"))
        self.label_7.setText(_translate("MainWindow", "Endereço de IP"))
        self.label_8.setText(_translate("MainWindow", "Mascara CIDR"))
        self.btncalcip.setText(_translate("MainWindow", "Calcular"))
        self.btnvoltar.setText(_translate("MainWindow", "Voltar"))
        self.label_5.setText(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.label_3.setText(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>"))
from calcula import calcdoc_rc
