# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'consulta_inter_erro.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(444, 368)
        MainWindow.setMinimumSize(QtCore.QSize(444, 368))
        MainWindow.setMaximumSize(QtCore.QSize(444, 368))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(20, 150, 411, 161))
        self.label_2.setObjectName("label_2")
        self.btnsair = QtWidgets.QPushButton(self.centralwidget)
        self.btnsair.setGeometry(QtCore.QRect(160, 300, 141, 28))
        self.btnsair.setObjectName("btnsair")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(50, 0, 401, 181))
        self.label.setStyleSheet("image: url(:/consultaerrodoc/ec9ca7f0d84780221389129e7adaccf1---cone-de-contato-de-bal--o-de-fala-de-informa----o-by-vexels.png);")
        self.label.setText("")
        self.label.setObjectName("label")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Mensagem"))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">Ops, </p><p align=\"center\">parece que não conseguimos localizar as infomações que você procura,</p><p align=\"center\">verifique a informação digitda e tente novamente,</p><p align=\"center\">caso necessário fale com o owner do sistema.</p></body></html>"))
        self.btnsair.setText(_translate("MainWindow", "Sair"))
from msg.todas.consulta import consultaerrodoc_rc
