# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'inserir_inter_erro.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(444, 368)
        MainWindow.setMinimumSize(QtCore.QSize(444, 368))
        MainWindow.setMaximumSize(QtCore.QSize(444, 368))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(110, 40, 221, 161))
        self.label.setStyleSheet("image: url(:/inserirerrodoc/440px-Achtung.svg.png);")
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(50, 220, 351, 71))
        self.label_2.setObjectName("label_2")
        self.btnok = QtWidgets.QPushButton(self.centralwidget)
        self.btnok.setGeometry(QtCore.QRect(150, 300, 141, 28))
        self.btnok.setObjectName("btnok")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Mensagem"))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">Voção não pode adicionar informação</p><p align=\"center\"> sem preencher os campos...</p></body></html>"))
        self.btnok.setText(_translate("MainWindow", "OK"))
from msg.todas.aualizando_inserindo.erro import inserirerrodoc_rc
