# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'analistas_inter.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(730, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(160, 50, 411, 91))
        self.label.setObjectName("label")
        self.btnvoltarconsulta = QtWidgets.QPushButton(self.centralwidget)
        self.btnvoltarconsulta.setGeometry(QtCore.QRect(91, 380, 93, 28))
        self.btnvoltarconsulta.setObjectName("btnvoltarconsulta")
        self.btnsairconsulta = QtWidgets.QPushButton(self.centralwidget)
        self.btnsairconsulta.setGeometry(QtCore.QRect(540, 380, 93, 28))
        self.btnsairconsulta.setObjectName("btnsairconsulta")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(260, 130, 301, 221))
        self.label_2.setStyleSheet("image: url(:/analistas/669174522bc5f8547a520aff4fd05644d3b4b3dcd35038f3391de14ac28daad8.png);")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.btnconsultar = QtWidgets.QPushButton(self.centralwidget)
        self.btnconsultar.setGeometry(QtCore.QRect(320, 380, 93, 28))
        self.btnconsultar.setObjectName("btnconsultar")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(90, 419, 551, 141))
        self.textBrowser.setObjectName("textBrowser")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(290, 20, 141, 51))
        self.label_4.setStyleSheet("image: url(:/analistas/scania-logo-2.png);")
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(100, 170, 76, 157))
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.vinhedo = QtWidgets.QRadioButton(self.widget)
        self.vinhedo.setObjectName("vinhedo")
        self.buttonGroup = QtWidgets.QButtonGroup(MainWindow)
        self.buttonGroup.setObjectName("buttonGroup")
        self.buttonGroup.addButton(self.vinhedo)
        self.gridLayout.addWidget(self.vinhedo, 1, 0, 1, 1)
        self.maua = QtWidgets.QRadioButton(self.widget)
        self.maua.setObjectName("maua")
        self.buttonGroup.addButton(self.maua)
        self.gridLayout.addWidget(self.maua, 2, 0, 1, 1)
        self.suvesa = QtWidgets.QRadioButton(self.widget)
        self.suvesa.setObjectName("suvesa")
        self.buttonGroup.addButton(self.suvesa)
        self.gridLayout.addWidget(self.suvesa, 6, 0, 1, 1)
        self.codema = QtWidgets.QRadioButton(self.widget)
        self.codema.setObjectName("codema")
        self.buttonGroup.addButton(self.codema)
        self.gridLayout.addWidget(self.codema, 4, 0, 1, 1)
        self.cavese = QtWidgets.QRadioButton(self.widget)
        self.cavese.setObjectName("cavese")
        self.buttonGroup.addButton(self.cavese)
        self.gridLayout.addWidget(self.cavese, 5, 0, 1, 1)
        self.litc = QtWidgets.QRadioButton(self.widget)
        self.litc.setObjectName("litc")
        self.buttonGroup.addButton(self.litc)
        self.gridLayout.addWidget(self.litc, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Arches 1.0 Consulta de Equipes"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600;\">Qual equipe gostaria de consultar?</span></p></body></html>"))
        self.btnvoltarconsulta.setText(_translate("MainWindow", "Voltar"))
        self.btnsairconsulta.setText(_translate("MainWindow", "Sair"))
        self.btnconsultar.setText(_translate("MainWindow", "Consultar"))
        self.vinhedo.setText(_translate("MainWindow", "Vinhedo"))
        self.maua.setText(_translate("MainWindow", "Mauá"))
        self.suvesa.setText(_translate("MainWindow", "Suvesa"))
        self.codema.setText(_translate("MainWindow", "Codema"))
        self.cavese.setText(_translate("MainWindow", "Cavese"))
        self.litc.setText(_translate("MainWindow", "Litc"))
from analistas import analistasdoc_rc
