# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'cadastro_inter_erro.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(444, 368)
        MainWindow.setMinimumSize(QtCore.QSize(444, 368))
        MainWindow.setMaximumSize(QtCore.QSize(444, 368))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(110, 40, 221, 161))
        self.label.setStyleSheet("image: url(:/cadastro_inter_errodoc/pagamento-retorno-sucesso.png);")
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(70, 200, 301, 71))
        self.label_2.setObjectName("label_2")
        self.btnsair = QtWidgets.QPushButton(self.centralwidget)
        self.btnsair.setGeometry(QtCore.QRect(90, 300, 111, 28))
        self.btnsair.setObjectName("btnsair")
        self.tbnovo = QtWidgets.QPushButton(self.centralwidget)
        self.tbnovo.setGeometry(QtCore.QRect(250, 300, 111, 28))
        self.tbnovo.setObjectName("tbnovo")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Mensagem"))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">O cadastro foi realizado com sucesso!!!</span></p></body></html>"))
        self.btnsair.setText(_translate("MainWindow", "Sair"))
        self.tbnovo.setText(_translate("MainWindow", "Novo cadastro"))
from msg.todas.cadastro import cadastro_inter_errodoc_rc
